# load sample

In [1]:
import pandas as pd
from pathlib import Path
import json

# get sample ids
sample_path = Path("../../data/sample/sample_tuning_10per.json")

with open(sample_path, "r") as f:
    sample_info = json.load(f)

#sample_ids = pd.DataFrame(sample_info["sample"])
sample_info.keys()

dict_keys(['sample_source', 'input_data', 'sampling', 'sampling_by_stratum', 'sample'])

In [3]:
#sample_info["sampling_by_stratum"]
sampling = pd.DataFrame(sample_info["sampling_by_stratum"])

sampling

,dominant_field,text_type,population,sample,fraction,percentage
0,Agricultural and Biological Sciences,abstract,3296,330.0,0.100121,10.012136
1,Agricultural and Biological Sciences,title,437,44.0,0.100686,10.068650
2,Arts and Humanities,abstract,93561,9356.0,0.099999,9.999893
3,Arts and Humanities,title,15231,1523.0,0.099993,9.999343
4,"Biochemistry, Genetics and Molecular Biology",abstract,1990,199.0,0.100000,10.000000
5,"Biochemistry, Genetics and Molecular Biology",title,248,25.0,0.100806,10.080645
6,"Business, Management and Accounting",abstract,9612,961.0,0.099979,9.997919
7,"Business, Management and Accounting",title,1482,148.0,0.099865,9.986505
8,Chemical Engineering,abstract,10,1.0,0.100000,10.000000
9,Chemistry,abstract,149,15.0,0.100671,10.067114
10,Chemistry,title,14,1.0,0.071429,7.142857
11,Computer Science,abstract,20396,2040.0,0.100020,10.001961
12,Computer Science,title,4401,440.0,0.099977,9.997728
13,Decision Sciences,abstract,1841,184.0,0.099946,9.994568
14,Decision Sciences,title,267,27.0,0.101124,10.112360
15,Dentistry,abstract,257,26.0,0.101167,10.116732
16,Dentistry,title,22,2.0,0.090909,9.090909
17,Earth and Planetary Sciences,abstract,1137,114.0,0.100264,10.026385
18,Earth and Planetary Sciences,title,133,13.0,0.097744,9.774436
19,"Economics, Econometrics and Finance",abstract,6904,690.0,0.099942,9.994206
20,"Economics, Econometrics and Finance",title,945,94.0,0.099471,9.947090
21,Energy,abstract,342,34.0,0.099415,9.941520
22,Energy,title,50,5.0,0.100000,10.000000
23,Engineering,abstract,3201,320.0,0.099969,9.996876
24,Engineering,title,444,44.0,0.099099,9.909910
25,Environmental Science,abstract,6246,625.0,0.100064,10.006404
26,Environmental Science,title,1017,102.0,0.100295,10.029499
27,Health Professions,abstract,15684,1568.0,0.099974,9.997450
28,Health Professions,title,2667,267.0,0.100112,10.011249
29,Immunology and Microbiology,abstract,282,28.0,0.099291,9.929078
30,Immunology and Microbiology,title,28,3.0,0.107143,10.714286
31,Materials Science,abstract,98,10.0,0.102041,10.204082
32,Materials Science,title,8,1.0,0.125000,12.500000
33,Mathematics,abstract,431,43.0,0.099768,9.976798
34,Mathematics,title,38,4.0,0.105263,10.526316
35,Medicine,abstract,26021,2602.0,0.099996,9.999616
36,Medicine,title,3850,385.0,0.100000,10.000000
37,Neuroscience,abstract,4374,437.0,0.099909,9.990855
38,Neuroscience,title,616,62.0,0.100649,10.064935
39,Nursing,abstract,846,85.0,0.100473,10.047281
40,Nursing,title,165,16.0,0.096970,9.696970
41,"Pharmacology, Toxicology and Pharmaceutics",abstract,238,24.0,0.100840,10.084034
42,"Pharmacology, Toxicology and Pharmaceutics",title,32,3.0,0.093750,9.375000
43,Physics and Astronomy,abstract,986,99.0,0.100406,10.040568
44,Physics and Astronomy,title,96,10.0,0.104167,10.416667
45,Psychology,abstract,39278,3928.0,0.100005,10.000509
46,Psychology,title,7373,737.0,0.099959,9.995931
47,Social Sciences,abstract,189913,18991.0,0.099998,9.999842
48,Social Sciences,title,31867,3187.0,0.100009,10.000941
49,Veterinary,abstract,45,4.0,0.088889,8.888889
50,Veterinary,title,5,0.0,0.000000,0.000000
51,NaN,abstract,525,53.0,0.100952,10.095238
52,NaN,title,91,9.0,0.098901,9.890110

In [9]:
table = sampling.pivot(
    index="dominant_field",
    columns="text_type",
    values=["sample", "percentage"]
)

def format_cell(sample, percentage):
    if pd.isna(sample) or pd.isna(percentage):
        return "--"
    return f"{sample:,.0f} ({percentage:.1f}\\%)"

formatted = pd.DataFrame(index=table.index)

for text_type in ["abstract", "title"]:
    formatted[text_type] = [
        format_cell(sample, percentage)
        for sample, percentage in zip(
            table[("sample", text_type)],
            table[("percentage", text_type)]
        )
    ]

formatted = formatted.rename(columns={
    "abstract": "Abstract",
    "title": "Title"
})

In [10]:
formatted

                                                     Abstract           Title
dominant_field
NaN                                               53 (10.1\%)       9 (9.9\%)
Agricultural and Biological Sciences             330 (10.0\%)     44 (10.1\%)
Arts and Humanities                            9,356 (10.0\%)  1,523 (10.0\%)
Biochemistry, Genetics and Molecular Biology     199 (10.0\%)     25 (10.1\%)
Business, Management and Accounting              961 (10.0\%)    148 (10.0\%)
Chemical Engineering                               1 (10.0\%)              --
Chemistry                                         15 (10.1\%)       1 (7.1\%)
Computer Science                               2,040 (10.0\%)    440 (10.0\%)
Decision Sciences                                184 (10.0\%)     27 (10.1\%)
Dentistry                                         26 (10.1\%)       2 (9.1\%)
Earth and Planetary Sciences                     114 (10.0\%)      13 (9.8\%)
Economics, Econometrics and Finance              690 (10.0\%)      94 (9.9\%)
Energy                                             34 (9.9\%)      5 (10.0\%)
Engineering                                      320 (10.0\%)      44 (9.9\%)
Environmental Science                            625 (10.0\%)    102 (10.0\%)
Health Professions                             1,568 (10.0\%)    267 (10.0\%)
Immunology and Microbiology                        28 (9.9\%)      3 (10.7\%)
Materials Science                                 10 (10.2\%)      1 (12.5\%)
Mathematics                                       43 (10.0\%)      4 (10.5\%)
Medicine                                       2,602 (10.0\%)    385 (10.0\%)
Neuroscience                                     437 (10.0\%)     62 (10.1\%)
Nursing                                           85 (10.0\%)      16 (9.7\%)
Pharmacology, Toxicology and Pharmaceutics        24 (10.1\%)       3 (9.4\%)
Physics and Astronomy                             99 (10.0\%)     10 (10.4\%)
Psychology                                     3,928 (10.0\%)    737 (10.0\%)
Social Sciences                               18,991 (10.0\%)  3,187 (10.0\%)
Veterinary                                          4 (8.9\%)       0 (0.0\%)

In [11]:
latex = formatted.to_latex(
    escape=False,
    index=True,
    column_format="lrr",
    header=True
)

print(latex)

\begin{tabular}{lrr}
\toprule
 & Abstract & Title \\
dominant_field &  &  \\
\midrule
NaN & 53 (10.1\%) & 9 (9.9\%) \\
Agricultural and Biological Sciences & 330 (10.0\%) & 44 (10.1\%) \\
Arts and Humanities & 9,356 (10.0\%) & 1,523 (10.0\%) \\
Biochemistry, Genetics and Molecular Biology & 199 (10.0\%) & 25 (10.1\%) \\
Business, Management and Accounting & 961 (10.0\%) & 148 (10.0\%) \\
Chemical Engineering & 1 (10.0\%) & -- \\
Chemistry & 15 (10.1\%) & 1 (7.1\%) \\
Computer Science & 2,040 (10.0\%) & 440 (10.0\%) \\
Decision Sciences & 184 (10.0\%) & 27 (10.1\%) \\
Dentistry & 26 (10.1\%) & 2 (9.1\%) \\
Earth and Planetary Sciences & 114 (10.0\%) & 13 (9.8\%) \\
Economics, Econometrics and Finance & 690 (10.0\%) & 94 (9.9\%) \\
Energy & 34 (9.9\%) & 5 (10.0\%) \\
Engineering & 320 (10.0\%) & 44 (9.9\%) \\
Environmental Science & 625 (10.0\%) & 102 (10.0\%) \\
Health Professions & 1,568 (10.0\%) & 267 (10.0\%) \\
Immunology and Microbiology & 28 (9.9\%) & 3 (10.7\%) \\
Materials Science & 10 (10.2\%) & 1 (12.5\%) \\
Mathematics & 43 (10.0\%) & 4 (10.5\%) \\
Medicine & 2,602 (10.0\%) & 385 (10.0\%) \\
Neuroscience & 437 (10.0\%) & 62 (10.1\%) \\
Nursing & 85 (10.0\%) & 16 (9.7\%) \\
Pharmacology, Toxicology and Pharmaceutics & 24 (10.1\%) & 3 (9.4\%) \\
Physics and Astronomy & 99 (10.0\%) & 10 (10.4\%) \\
Psychology & 3,928 (10.0\%) & 737 (10.0\%) \\
Social Sciences & 18,991 (10.0\%) & 3,187 (10.0\%) \\
Veterinary & 4 (8.9\%) & 0 (0.0\%) \\
\bottomrule
\end{tabular}

In [15]:
sum(table["sample"]["abstract"])

42767.0

In [16]:
sum(table["sample"]["title"])

nan